apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: observability-awx
  namespace: awx
spec:
  service_type: NodePort
  nodeport_port: 30080
  ingress_type: none
  api_urlpattern_prefix: /awx
  admin_user: admin
  admin_email: admin@localhost
  postgres_storage_class: local-path
  postgres_storage_requirements:
    requests:
      storage: 8Gi
  task_resource_requirements:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  web_resource_requirements:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  postgres_resource_requirements:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
