apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
data:
  mimir.yaml: |
    multitenancy_enabled: false
    target: all

    server:
      http_listen_port: 9009

    blocks_storage:
      backend: s3
      storage_prefix: blocks
      s3:
        endpoint: garage.storage.svc.cluster.local:3900
        bucket_name: mimir-blocks
        access_key_id: eeb12a6b2ee2be3623c17ec3aa5f994c
        secret_access_key: fc121e860c2ec4c30ffd5d244f9ee47e
        insecure: true
        bucket_lookup_type: path
      bucket_store:
        sync_dir: /data/tsdb-sync

    compactor:
      data_dir: /data/compactor

    ingester:
      ring:
        replication_factor: 1
        kvstore:
          store: memberlist

    distributor:
      ring:
        kvstore:
          store: memberlist

    store_gateway:
      sharding_ring:
        replication_factor: 1

    ruler_storage:
      backend: local
      local:
        directory: /data/ruler

    alertmanager_storage:
      backend: local
      local:
        path: /data/alertmanager
